/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}', './tests/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { desktop: '1440px' } },
    extend: {
      fontFamily: { sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'] },
      fontWeight: { regular: '400', medium: '500', semibold: '600', bold: '700' },
      fontSize: {
        'style-page-title': ['28px', '36px'], 'style-page-subtitle': ['14px', '22px'],
        'style-section-title': ['20px', '28px'], 'style-subsection-title': ['16px', '24px'],
        'style-card-title': ['14px', '20px'], 'style-dialog-title': ['18px', '26px'],
        'style-empty-title': ['16px', '24px'], 'style-body-large': ['16px', '24px'],
        'style-body': ['14px', '22px'], 'style-body-small': ['13px', '20px'],
        'style-caption': ['12px', '18px'], 'style-legal': ['11px', '16px'],
        'style-field-label': ['13px', '18px'], 'style-field-value': ['14px', '20px'],
        'style-button-label': ['13px', '18px'], 'style-button-label-compact': ['12px', '16px'],
        'style-nav-item': ['13px', '18px'], 'style-tab-label': ['13px', '18px'],
        'style-metric-hero': ['28px', '34px'], 'style-chart-micro': ['10px', '14px'],
      },
      colors: {
        canvas: 'var(--sys-color-canvas)', surface: 'var(--sys-color-surface)',
        'surface-subtle': 'var(--sys-color-surface-subtle)', 'surface-hover': 'var(--sys-color-surface-hover)',
        'text-primary': 'var(--sys-color-text-primary)', 'text-secondary': 'var(--sys-color-text-secondary)', 'text-muted': 'var(--sys-color-text-muted)',
        disabled: 'var(--sys-color-disabled)', 'disabled-soft': 'var(--sys-color-disabled-soft)',
        border: 'var(--border)', 'border-divider': 'var(--sys-color-border-divider)', 'border-subtle': 'var(--sys-color-border-subtle)',
        'border-hover': 'var(--sys-color-border-hover)', 'border-control': 'var(--sys-color-border-control-essential)',
        input: 'var(--input)', ring: 'var(--ring)',
        primary: { DEFAULT: 'var(--sys-color-action-primary)', hover: 'var(--sys-color-action-primary-hover)', pressed: 'var(--sys-color-action-primary-pressed)', focus: 'var(--sys-color-action-primary-focus)', soft: 'var(--sys-color-action-primary-soft)', border: 'var(--sys-color-action-primary-border)', foreground: 'var(--sys-color-on-primary)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        error: 'var(--sys-color-error)', 'error-soft': 'var(--sys-color-error-soft)', 'error-border': 'var(--sys-color-error-border)',
        success: 'var(--sys-color-success)', 'success-soft': 'var(--sys-color-success-soft)', 'success-border': 'var(--sys-color-success-border)',
        warning: 'var(--sys-color-warning)', 'warning-soft': 'var(--sys-color-warning-soft)', 'warning-border': 'var(--sys-color-warning-border)',
        info: 'var(--sys-color-info)', 'info-soft': 'var(--sys-color-info-soft)', 'info-border': 'var(--sys-color-info-border)',
        'on-primary': 'var(--sys-color-on-primary)',
        'macro-protein': 'var(--sys-color-macro-protein)', 'macro-protein-soft': 'var(--sys-color-macro-protein-soft)', 'macro-protein-border': 'var(--sys-color-macro-protein-border)',
        'macro-carbohydrate': 'var(--sys-color-macro-carbohydrate)', 'macro-carbohydrate-soft': 'var(--sys-color-macro-carbohydrate-soft)', 'macro-carbohydrate-border': 'var(--sys-color-macro-carbohydrate-border)',
        'macro-fat': 'var(--sys-color-macro-fat)', 'macro-fat-soft': 'var(--sys-color-macro-fat-soft)', 'macro-fat-border': 'var(--sys-color-macro-fat-border)',
      },
      spacing: { sidebar: '224px', 'sidebar-collapsed': '64px' },
      borderRadius: { compact: 'var(--sys-radius-compact)', control: 'var(--sys-radius-control)', surface: 'var(--sys-radius-surface)', round: 'var(--sys-radius-round)' },
      height: { 'control-compact': '32px', 'control-standard': '36px', 'table-row': '44px' },
      transitionDuration: { fast: 'var(--sys-motion-fast)', standard: 'var(--sys-motion-standard)', slow: 'var(--sys-motion-slow)' },
      transitionTimingFunction: { standard: 'var(--sys-ease-standard)', exit: 'var(--sys-ease-exit)' },
      opacity: { disabled: 'var(--sys-opacity-disabled)' },
      zIndex: { base: '0', raised: '10', sticky: '20', navigation: '30', dropdown: '40', popover: '50', overlay: '60', modal: '70', toast: '80', tooltip: '90' },
      letterSpacing: { tight: '-0.01em', label: '0.04em', overline: '0.06em' },
    },
  },
  plugins: [],
};
