/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}', './tests/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { desktop: '1440px' } },
    extend: {
      fontFamily: { sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'] },
      fontWeight: { regular: '400', medium: '500', semibold: '600', bold: '700' },
      fontSize: {
        'style-page-title': ['28px', '36px'], 'style-page-subtitle': ['14px', '22px'],
        'style-section-title': ['20px', '28px'], 'style-subsection-title': ['16px', '24px'],
        'style-card-title': ['14px', '20px'], 'style-dialog-title': ['18px', '26px'],
        'style-empty-title': ['16px', '24px'], 'style-body-large': ['16px', '24px'],
        'style-body': ['14px', '22px'], 'style-body-small': ['13px', '20px'],
        'style-caption': ['12px', '18px'], 'style-legal': ['11px', '16px'],
        'style-field-label': ['13px', '18px'], 'style-field-value': ['14px', '20px'],
        'style-button-label': ['13px', '18px'], 'style-button-label-compact': ['12px', '16px'],
        'style-nav-item': ['13px', '18px'], 'style-tab-label': ['13px', '18px'],
        'style-metric-hero': ['28px', '34px'], 'style-chart-micro': ['10px', '14px'],
      },
      colors: {
        canvas: 'var(--sys-color-canvas)', surface: 'var(--sys-color-surface)',
        'surface-subtle': 'var(--sys-color-surface-subtle)', 'surface-soft': 'var(--sys-color-surface-soft)', 'surface-hover': 'var(--sys-color-surface-hover)',
        'text-primary': 'var(--sys-color-text-primary)', 'text-secondary': 'var(--sys-color-text-secondary)', 'text-muted': 'var(--sys-color-text-muted)',
        disabled: 'var(--sys-color-disabled)', 'disabled-soft': 'var(--sys-color-disabled-soft)',
        border: 'var(--border)', 'border-divider': 'var(--sys-color-border-divider)', 'border-subtle': 'var(--sys-color-border-subtle)',
        'border-hover': 'var(--sys-color-border-hover)', 'border-control': 'var(--sys-color-border-control-essential)',
        'button-secondary-hover': 'var(--cmp-button-secondary-background-hover)', 'button-secondary-border-hover': 'var(--cmp-button-secondary-border-hover)',
        'card-background-hover': 'var(--cmp-card-background-hover)',
        'card-details-surface': 'var(--cmp-card-details-surface)',
        input: 'var(--input)', ring: 'var(--ring)',
        primary: { DEFAULT: 'var(--sys-color-action-primary)', hover: 'var(--sys-color-action-primary-hover)', pressed: 'var(--sys-color-action-primary-pressed)', focus: 'var(--sys-color-action-primary-focus)', soft: 'var(--sys-color-action-primary-soft)', border: 'var(--sys-color-action-primary-border)', foreground: 'var(--sys-color-on-primary)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        error: 'var(--sys-color-error)', 'error-soft': 'var(--sys-color-error-soft)', 'error-border': 'var(--sys-color-error-border)',
        success: 'var(--sys-color-success)', 'success-soft': 'var(--sys-color-success-soft)', 'success-border': 'var(--sys-color-success-border)',
        warning: { DEFAULT: 'var(--sys-color-warning)', pressed: 'var(--sys-color-warning-pressed)', soft: 'var(--sys-color-warning-soft)', border: 'var(--sys-color-warning-border)' },
        info: 'var(--sys-color-info)', 'info-soft': 'var(--sys-color-info-soft)', 'info-border': 'var(--sys-color-info-border)',
        'on-primary': 'var(--sys-color-on-primary)',
        'on-error': 'var(--sys-color-on-error)',
        'on-warning': 'var(--sys-color-on-warning)',
        'on-success': 'var(--sys-color-on-success)',
        'on-info': 'var(--sys-color-on-info)',
        'backdrop-overlay': 'var(--sys-backdrop-overlay)',
        'macro-protein': 'var(--sys-color-macro-protein)', 'macro-protein-soft': 'var(--sys-color-macro-protein-soft)', 'macro-protein-border': 'var(--sys-color-macro-protein-border)',
        'macro-carbohydrate': 'var(--sys-color-macro-carbohydrate)', 'macro-carbohydrate-soft': 'var(--sys-color-macro-carbohydrate-soft)', 'macro-carbohydrate-border': 'var(--sys-color-macro-carbohydrate-border)',
        'macro-fat': 'var(--sys-color-macro-fat)', 'macro-fat-soft': 'var(--sys-color-macro-fat-soft)', 'macro-fat-border': 'var(--sys-color-macro-fat-border)',
        'macro-kcal': 'var(--sys-color-macro-kcal)', 'macro-kcal-soft': 'var(--sys-color-macro-kcal-soft)', 'macro-kcal-border': 'var(--sys-color-macro-kcal-border)',
        sidebar: {
          DEFAULT: 'var(--cmp-sidebar-background)',
          foreground: 'var(--cmp-sidebar-foreground)',
          primary: 'var(--cmp-sidebar-primary)',
          'primary-foreground': 'var(--cmp-sidebar-primary-foreground)',
          'primary-soft': 'var(--cmp-sidebar-primary-soft)',
          accent: 'var(--cmp-sidebar-accent)',
          'accent-foreground': 'var(--cmp-sidebar-accent-foreground)',
          border: 'var(--cmp-sidebar-border)',
          ring: 'var(--cmp-sidebar-ring)',
        },
      },
      spacing: { sidebar: 'var(--cmp-sidebar-width-expanded)', 'sidebar-collapsed': 'var(--cmp-sidebar-width-collapsed)' },
      maxWidth: { 'container-page': '1440px', 'container-workflow': '1200px', 'container-form': '960px', 'container-reading': '720px' },
      maxHeight: {
        dialog: 'var(--cmp-dialog-max-height)',
        'table-compact': 'var(--cmp-data-table-max-height-compact)',
        'table-modal': 'var(--cmp-data-table-max-height-modal)',
        'table-compact-body': 'var(--cmp-data-table-max-height-compact-body)',
        'table-modal-body': 'var(--cmp-data-table-max-height-modal-body)',
      },
      minHeight: { 'table-modal': 'var(--cmp-data-table-max-height-modal)' },
      borderRadius: { compact: 'var(--sys-radius-compact)', control: 'var(--sys-radius-control)', surface: 'var(--sys-radius-surface)', round: 'var(--sys-radius-round)' },
      boxShadow: { floating: 'var(--sys-shadow-floating)', overlay: 'var(--sys-shadow-overlay)' },
      height: {
        'control-compact': '32px',
        'control-standard': '36px',
        'table-row': '44px',
        'table-row-food': 'var(--cmp-data-table-row-height-food)',
      },
      width: {
        'control-compact': '32px',
        'control-standard': '36px',
        'meal-title': 'var(--cmp-meal-title-input-width)',
      },
      transitionDuration: {
        fast: 'var(--sys-motion-fast)',
        standard: 'var(--sys-motion-standard)',
        slow: 'var(--sys-motion-slow)',
        hold: 'var(--cmp-hold-to-delete-progress-duration)',
      },
      transitionProperty: { width: 'width' },
      transitionTimingFunction: { standard: 'var(--sys-ease-standard)', exit: 'var(--sys-ease-exit)' },
      opacity: { disabled: 'var(--sys-opacity-disabled)', subdued: '0.72', full: '1' },
      zIndex: { base: '0', raised: '10', sticky: '20', navigation: '30', dropdown: '40', popover: '50', overlay: '60', modal: '70', toast: '80', tooltip: '90' },
      letterSpacing: { tight: '-0.01em', label: '0.04em', overline: '0.06em' },
    },
  },
  plugins: [],
};
